/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSubredditSortRouteImport } from './routes/r/$subreddit.$sort'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSubredditSortRoute = RSubredditSortRouteImport.update({
  id: '/r/$subreddit/$sort',
  path: '/r/$subreddit/$sort',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$subreddit/$sort': typeof RSubredditSortRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$subreddit/$sort': typeof RSubredditSortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/$subreddit/$sort': typeof RSubredditSortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r/$subreddit/$sort'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/r/$subreddit/$sort'
  id: '__root__' | '/' | '/r/$subreddit/$sort'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RSubredditSortRoute: typeof RSubredditSortRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$subreddit/$sort': {
      id: '/r/$subreddit/$sort'
      path: '/r/$subreddit/$sort'
      fullPath: '/r/$subreddit/$sort'
      preLoaderRoute: typeof RSubredditSortRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RSubredditSortRoute: RSubredditSortRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
